name: Publish and Release

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build
      # - uses: JS-DevTools/npm-publish@v1
      #   with:
      #     token: ${{ secrets.NPM_TOKEN }}
      #     access: public
      - name: Create Release Files
        run: yarn release:all
      - name: Get Version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
      - uses: cb80/pubrel@latest
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          replace: latest
          files: |
            release/nusage-linux-x64
            release/nusage-linux-x86
            release/nusage-macos
            release/nusage-win32-x64.exe
            release/nusage-win32-x86.exe
